/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as EmailRouteImport } from './routes/email'
import { Route as LivestockRouteImport } from './routes/livestock'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestockRoute = LivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crops': typeof CropsRoute
  '/email': typeof EmailRoute
  '/livestock': typeof LivestockRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crops': typeof CropsRoute
  '/email': typeof EmailRoute
  '/livestock': typeof LivestockRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crops': typeof CropsRoute
  '/email': typeof EmailRoute
  '/livestock': typeof LivestockRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/crops'
    | '/email'
    | '/livestock'
    | '/meetings'
    | '/research'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/crops'
    | '/email'
    | '/livestock'
    | '/meetings'
    | '/research'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/crops'
    | '/email'
    | '/livestock'
    | '/meetings'
    | '/research'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CropsRoute: typeof CropsRoute
  EmailRoute: typeof EmailRoute
  LivestockRoute: typeof LivestockRoute
  MeetingsRoute: typeof MeetingsRoute
  ResearchRoute: typeof ResearchRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestock': {
      id: '/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof LivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CropsRoute: CropsRoute,
  EmailRoute: EmailRoute,
  LivestockRoute: LivestockRoute,
  MeetingsRoute: MeetingsRoute,
  ResearchRoute: ResearchRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
